# =============================================================================
# ledge-service.env.tpl — Ledge 服务独有变量
# 与 shared.env 合并后生成 ledge-service.env
# =============================================================================

# --- X402 支付框架 ---
X402_DEFAULT_ASSET=<请替换>
X402_DEFAULT_NETWORK=<请替换>
X402_DEFAULT_SCHEME=<请替换>
X402_DEFAULT_FACILITATOR=<请替换>
X402_BASE_NETWORK_SLUG=<请替换>
X402_PUBLIC_BASE_URL=<请替换>
X402_SELF_HOSTED_BASE_URL=<请替换>
X402_SELF_HOSTED_AUTH_TOKEN=<请替换>
X402_COINBASE_API_KEY_ID=<请替换>
X402_COINBASE_API_KEY_SECRET=<请替换>
X402_COINBASE_BASE_URL=<请替换>
X402_FACILITATOR_BY_NETWORK__eip155_84532=<请替换>
X402_FACILITATOR_BY_NETWORK__solana_mainnet=<请替换>

# --- Managed Wallets 独有 ---
MANAGED_WALLETS_DEFAULT_PROVIDER=<请替换>
MANAGED_WALLETS_WORKSPACE_ACCESS_MODE=<请替换>
MANAGED_WALLETS_ALLOWED_WORKSPACES=<请替换>
MANAGED_WALLETS_DAILY_WITHDRAWAL_MINOR_AMOUNT=<请替换>
MANAGED_WALLETS_MAX_WITHDRAWAL_MINOR_AMOUNT=<请替换>
MANAGED_WALLETS_DEPOSIT_CREATE_ENABLED=true
MANAGED_WALLETS_DEPOSIT_SUBMIT_ENABLED=true
MANAGED_WALLETS_WITHDRAW_CREATE_ENABLED=true
MANAGED_WALLETS_REVENUE_WITHDRAW_CREATE_ENABLED=true
MANAGED_WALLETS_REVENUE_WITHDRAW_NETWORK_FEE_MINOR_AMOUNT=<请替换>
MANAGED_WALLETS_TRANSFER_SUBMIT_ENABLED=true
MANAGED_WALLETS_TRANSFER_REFRESH_ENABLED=true
MANAGED_WALLETS_BASE_RPC_URL=<请替换>
MANAGED_WALLETS_BASE_WS_URL=<请替换>
MANAGED_WALLETS_BASE_MIN_NATIVE_GAS_WEI=<请替换>
MANAGED_WALLETS_BASE_TARGET_NATIVE_GAS_WEI=<请替换>
MANAGED_WALLETS_SOLANA_RPC_URL=<请替换>
MANAGED_WALLETS_SOLANA_WS_URL=<请替换>
MANAGED_WALLETS_SOLANA_MIN_NATIVE_GAS_LAMPORTS=<请替换>
MANAGED_WALLETS_SOLANA_TARGET_NATIVE_GAS_LAMPORTS=<请替换>
MANAGED_WALLETS_PROVIDER_BY_NETWORK__BASE=<请替换>
MANAGED_WALLETS_PROVIDER_BY_NETWORK__SOLANA=<请替换>

# --- CDP Wallet ---
CDP_WALLET_API_KEY_ID=<请替换>
CDP_WALLET_API_KEY_SECRET=<请替换>
CDP_WALLET_SECRET=<请替换>

# --- Payment 独有 ---
PAYMENT_SERVICE_ENV=production
PAYMENT_INTERNAL_AUTH_TOKEN=<请替换>
PAYMENT_LOGS_COLLECTOR_URL=http://logs-collector:8585
PAYMENT_REDIS_STREAM_PREFIX=payment:
PAYMENT_SIDECAR_SIM_BASE_NETWORK_SLUG=<请替换>
PAYMENT_WORKERS_ENABLED=true
