# =============================================================================
# saas-service.env.tpl — SaaS 后端独有变量
# 与 shared.env 合并后生成 saas-service.env
# 由 generate-envs.sh 自动处理
# =============================================================================

# --- 基础 ---
APP_BASE_URL=https://your-domain.com
ENV=production
MASTER_KEY=<请替换>
ENABLE_SWAGGER_UI=false

# --- Redis 专属配置 ---
REDIS_KEY_PREFIX=alephant:
REDIS_LOCK_DEFAULT_TTL_SECONDS=30
REDIS_LOCK_RENEW_INTERVAL_SECONDS=10
REDIS_STRONG_COORDINATION=true
IDEMPOTENCY_TTL_SECONDS=86400
LAST_USED_DEBOUNCE_SECONDS=5

# --- Cookie / Session ---
REFRESH_COOKIE_NAME=refresh_token
REFRESH_COOKIE_HTTP_ONLY=true
REFRESH_COOKIE_SAME_SITE=lax
REFRESH_COOKIE_SECURE=true

# --- JWT ---
JWT_ACCESS_TTL=900
JWT_REFRESH_TTL=604800
CSRF_TOKEN_TTL=3600

# --- Stripe 支付 ---
STRIPE_SECRET_KEY=<请替换>
STRIPE_WEBHOOK_SECRET=<请替换>
STRIPE_PRICE_PRO_MONTHLY=<请替换>
STRIPE_PRICE_PRO_YEARLY=<请替换>
STRIPE_PRICE_TEAM_MONTHLY=<请替换>
STRIPE_PRICE_TEAM_YEARLY=<请替换>
STRIPE_PRICE_ENTERPRISE_MONTHLY=<请替换>
STRIPE_PRICE_ENTERPRISE_YEARLY=<请替换>
STRIPE_PRICE_EXTRA_VK=<请替换>
STRIPE_PRICE_LOG_PACK_PRO=<请替换>
STRIPE_PRICE_LOG_PACK_TEAM=<请替换>
STRIPE_PRICE_LOG_PACK_ENTERPRISE=<请替换>
STRIPE_METER_EVENT_LOG_PACK_PRO=<请替换>
STRIPE_METER_EVENT_LOG_PACK_TEAM=<请替换>
STRIPE_METER_EVENT_LOG_PACK_ENTERPRISE=<请替换>

# --- OAuth ---
OAUTH_GITHUB_CLIENT_ID=<请替换>
OAUTH_GITHUB_CLIENT_SECRET=<请替换>
OAUTH_GOOGLE_CLIENT_ID=<请替换>
OAUTH_GOOGLE_CLIENT_SECRET=<请替换>
OAUTH_GITHUB_ALLOWED_REDIRECT_URIS=<请替换>

# --- Managed Wallets 独有 ---
MANAGED_WALLETS_API_ENABLED=true
MANAGED_WALLETS_DAILY_WITHDRAW_LIMIT=<请替换>
MANAGED_WALLETS_MAX_WITHDRAW_AMOUNT=<请替换>

# --- Policy ---
POLICY_STREAM_MAXLEN=10000

# --- Analytics / Logs ---
COLLECTOR_ANALYTICS_BASE_URL=http://logs-collector:8585
LOG_OVERAGE_E2E_METER_EVENT_NAME=
LOG_OVERAGE_E2E_REAL_STRIPE=false
LOG_OVERAGE_E2E_STRIPE_CUSTOMER_ID=
REVENUE_WITHDRAW_API_ENABLED=true

# --- 其他 ---
ENFORCE_TRIAL_ONCE_PER_USER=false
AUTH_RATE_LIMIT_PER_MIN=60
SALES_LEAD_EMAIL=<请替换>
